#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse

class MakeHTML:
    def __init__(self, bibtex_filename):
        self.bib = open(bibtex_filename, "r")
        self.ja_name = "河原塚健人"
        self.en_name = "Kentokawaharazuka"

        self.conference_name = {}

        self.journal_papers = []
        self.reviewed_iconference = []
        self.reviewed_dconference = []
        self.dconference = []

    def parse_bib(self):
        for line in self.bib:
            if line == "\n":
                continue
            if "@string" in line:
                name = line.split('{')[1].split(' ')[0]
                conference_name = line.split('"')[1]
                self.conference_name[name] = conference_name
            if line[0] == "%":
                print(line)
                continue

    def make_html(self, out_filename):
        hoge

def main():
    parser = argparse.ArgumentParser(
        description="make_html_from_bib")
    parser.add_argument('--file', '-f', type=str, default="main.bib",
                        help='bibtex file')
    parser.add_argument('--base', '-b', type=str, default="base.html",
                        help='base html file')
    parser.add_argument('--out', '-o', type=str, default="publication.html",
                        help='output html file')
    args = parser.parse_args()
    makeHTML = MakeHTML(args.file)
    makeHTML.parse_bib()
    makeHTML.make_html(args.out)

if __name__ == '__main__':
    main()
